server:
  port: 8083

eureka:
  client:
    service-url:
      defualt-zone: http://localhost:8761/

spring:
  application:
    name: ORDER-SERVICE

management:
  endpoint:
    health:
      show-details: "ALWAYS"
  endpoints:
    web:
      exposure:
        include: "*"